server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password:
      url: jdbc:mysql://localhost:3306/registration
      username:
    jpa:
      hibernate:
        ddl-auto:
         create-drop
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            format-sql: true
        show-sql: true
